### ISSUE TITLE
Other software of VM

### ISSUE THREAD

**Issue by RimiChen** [SoftwareEngineeringToolDemos/ICSE-2014-Atlas#9]
The instruction is the VM should not contain any proprietary software what are not strictly necessary.

For this instruction, I don't know whether the software which automatically be installed when you installed your system are "not necessary" or they are fine for this instruction.

Some software, like firefox (I know it will automatically be installed, when you install Linux system like Ubuntu) is not strict necessary, but it was very helpful to view the instruction video on youtube.

**Comment by sujithktkm** [comment]
Yes, Firefox is required. So I did not uninstall it. I removed unnecessary icons from sidebar and cleared startup processes that are not required.
